- name: play level variables
  hosts: local
  connection: local #Ansible will run the playbook on the local machine
  vars:
    NAME: "T DanaKamalakar"
    GENDER: "Male"
    LOCATION: "Kothagudem"
  tasks:
    - name: print the variables
      LOCATION: "Warangal"
      ansible.builtin.debug:
        msg: "My name is {{ NAME }}. I am a {{ GENDER }}. I live in {{ LOCATION }}."
