- name: variables from inventory
  hosts: local
  connection: local #Ansible will run the playbook on the local machine
  tasks:
    - name: print the variables from inventory
      ansible.builtin.debug:
        msg: "My name is {{ NAME }}. I am a {{ GENDER }}. I live in {{ LOCATION }}."